services:
  # ───────────────────── Python ─────────────────────
  python:
    container_name: python_runner
    build: ./python
    volumes:
      - .:/app
    command: >
      bash -c "python /app/daily_rates_ingestion.py && sleep infinity"
    restart: always
